FROM ubuntu:bionic

# OS Prereq install
RUN apt-get install sqlite3 libsqlite3-dev libgmp3-dev \
    apt-get install mysql-client libmysqlclient-dev mysql-server \
    apt-get install sphinxsearch memcached imagemagick transifex-client graphviz \
    apt-get install git
RUN mkdir hitobito

RUN git clone https://github.com/hitobito/hitobito.git \
    git clone https://github.com/hitobito/hitobito_generic.git \
    cp hitobito/Wagonfile.ci hitobito/Wagonfile \
    cp hitobito/Gemfile.lock hitobito_generic/
RUN cd hitobito \
    bundle \
    rake db:create \
    rake db:setup:all \
    gem install foreman \
    foreman start

RUN rake \
    rake wagon:test

